kind: Service
apiVersion: v1
metadata:
  name: hello-world-service
spec:
  selector:
    app: hello-world
  type: NodePort
  ports:
    - nodePort: 30950
      targetPort: 80
      port: 80
      protocol: TCP
